document:
  name: Guidelines on the acquisition and reuse of software for public administrations
  description: Guidelines on the acquisition and reuse of software for public administrations 
  tags:
    - guidelines 
    - reuse 
    - public code
